#!/bin/sh
monitor="SINGLE MONITOR 😗\nTWO MONITORS 😎😀\nDUPLICATE MONITORS 👽👽\nROTATED MONITOR 👽🙃"
chosen=$(echo -e $monitor | dmenu -i -l 7 -h 15 -fn Monospace-14 -sb "#d3869b" -sf "#504945" -nb "#504945" -nf "#fbf1c7")
if [ "${chosen:0:1}" == "S" ]; then 
  xrandr --output HDMI2 --off && xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal 
elif [ "${chosen:0:1}" == "D" ]; then 
  xrandr --output HDMI2 --primary --mode 1920x1080 --pos 0x0 --rotate normal && xrandr --output eDP1 --auto --same-as eDP1
elif [ "${chosen:0:1}" == "R" ]; then 
  xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal && xrandr --output HDMI2 --rotate right
elif [ "${chosen:0:1}" == "T" ]; then 
  xrandr --output HDMI2 --primary --mode 1920x1080 --pos 0x0 --rotate normal && xrandr --output eDP1 --auto --left-of HDMI2
else
    notify-send "Wrong setup!"
fi
notify-send $chosen
./.config/polybar/launch.sh
