#!/bin/sh

chosen=$(grep -v "#" ~/.monitors | dmenu -i -l 7 -h 15 -fn Monospace-18)
if [ "${chosen:0:1}" == "S" ]; then 
  xrandr --output HDMI2 --off && xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal && notify-send "Single monitor setup"
elif [ "${chosen:0:1}" == "D" ]; then 
  xrandr --output HDMI2 --primary --mode 1920x1080 --pos 0x0 --rotate normal && xrandr --output eDP1 --auto --same-as eDP1 && notify-send "Duplicated monitor setup" && ./.config/polybar/launch.sh
elif [ "${chosen:0:1}" == "R" ]; then 
  xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal && xrandr --output HDMI2 --rotate right && notify-send "Rotated monitor setup" && ./.config/polybar/launch.sh
else
  xrandr --output HDMI2 --primary --mode 1920x1080 --pos 0x0 --rotate normal && xrandr --output eDP1 --auto --left-of HDMI2 && notify-send "Double monitor setup" && ./.config/polybar/launch.sh
fi
